""" Basic Setup.


" File encoding
set encoding=utf-8
scriptencoding utf-8

" Disable vi compatibility
if &compatible
  set nocompatible
endif

" Warning for old versions
if v:version < 800
  let v:warningmsg = 'Vim version 8 or higher is required'
  echohl WarningMsg
  echomsg v:warningmsg
  echohl none
endif

" Error for neovim
if has('nvim')
  let v:errmsg = 'Does not work with neovim'
  echohl ErrorMsg
  echoerr v:errmsg
  echohl none
  cquit
endif

" Load remaining configurations

runtime vimrc.d/paths.vim       " Should be early
runtime vimrc.d/disabled.vim    " Disable unnecessary built-ins
runtime vimrc.d/dein.vim        " Configure and load plugins
runtime vimrc.d/settings.vim   " Should be first after dein
runtime vimrc.d/syntax.vim
runtime vimrc.d/misc.vim
runtime vimrc.d/maps.vim
runtime vimrc.d/packages.vim
runtime vimrc.d/localcfg.vim
